### ISSUE TITLE
Feasibility: PPT Play

### ISSUE THREAD

**Issue by Nik20112** [realm-demos/realm-draw#22]
Hi Realm Team,

I have successfully testing the drawing demo in multiple devices and its working fine vice versa case. I want to know that when I play the PPT file in one device and its reflect/play into other device or multiple device.

Please suggest me this feature. Is it feasible with realm mobile platform or not?

Best Regards,
Nikunj

**Comment by AndyDentFree** [comment]
Hii @Nik20112, I'm not sure what you are asking. By _PPT file_ do you mean the drawing?

If you mean, will it update multiple devices, the answer is very much yes. In my solo testing I have used as many as five devices at once (Apple Pencil in mouth to drive an iPad, two iPhones and two Android tablets).

The Realm server simply accepts input from all the devices connected to a given Realm and the devices are all updated to match.

If you wanted to change the app to only draw on some devices rather than accepting drawing input on that device, as a way to just _broadcast_  a drawing, that would be a simple change to the application logic so only one _master_ device accepted touch events. The others would then just draw whatever was drawn on the master.

**Comment by TimOliver** [comment]
Closing this as a duplicate issue of https://github.com/realm/realm-cocoa/issues/4751
